### PR TITLE
Jdp leap leaper classes

### LINKED ISSUE #3: Laboratory Class
# User Story

# DEV
* has a variable representing the budget (is a field).
* creates Leaps
* Pushes leaps to the Leap repo
* Has a method that allows the budget to get used, and prevents a negative integer. (e.g. AttemptLeap - creates leap, checks date diff, and checks to see if budget allows, and then if true, it pushes the Leap to the Leap Repo, set the Event from that leap to isPutRight = true, THEN run a method called ButterflyEffect).
* Run the ButterflyEffect method passing in the date of the successful leap.

### PR DESCRIPTION
**Pull request by jpantana**
closes #3

### CODE REVIEW

**Comment by samueltrejo** [comment]
🔥 👎 🔥

**Comment by tilleraj** [comment]
Issue mentions 
```
4 properties:
ID, Event ID, Host ID, Leaper ID
```
I'm seeing 
```
 public Guid ID { get; } = Guid.NewGuid();
 public string MyEvent { get; set; }
 public Event EventId { get; }
 public string Location { get; }
 public DateTime Date { get; }
 public Leaper Leaper { get; }
 public Host Host { get; }
```
Also anything with "ID" should be of type Guid

Just realized that all repositories will need to have a method to "get[object]ById" but that's an everyone thing and not just a you thing.

**Comment by jpantana** [comment]
It does, and i inherited the rest from a PR @tilleraj

**Comment by tilleraj** [comment]
👍

**Comment by samueltrejo** [comment]
👍

**Pull request merged**
