### PR TITLE
St userinterfacephase2

### LINKED ISSUE #8: UserInterface Class
# user story
as a user, I should have a way to interact with this app

# acceptance criteria
when launching this code,
then i should be prompted to choose a leaper
once i successfully type the name of a leaper
then i will be presented with options leap, history, fund, and home,
* home should exit the app
* history should log the leaps that have been made
* fund will prompt you to enter an amount and then log your entered amount
* and leap will log that the leap functionality has not yet been implemented

# dev
* The user interface is the way the user calls the methods of the classes
* present options (console), then listen for input, then act upon that input
* 4th option, quit.

### PR DESCRIPTION
**Pull request by samueltrejo**
implemented final ui changes, which includes clearing console to only show active information
added butterfly affect function call to leap method,
increased budget to 10 mil, which allows for inital even amount of low funds error and success messages
made a couple of spacing fixes in the console, and added some color

closes #8

### CODE REVIEW

**Comment by jpantana** [comment]
👍 , only i would recommend w change the language of the console that says we did or didn't change. It reads something like, "You changed Gamestop..." which is unclear to me. Maybe something like, "You changed the future by visiting...". Food for thought.

**Comment by samueltrejo** [comment]
so `you changed the future by visiting "current leap location"`, and not give which event we changed? or `you changed "future leap location", by visiting "current leap location"`

i agree though it's kinda wierd how it's currently worded

**Comment by samueltrejo** [comment]
@jpantana fixed, in response to your butterfly effect wording suggestion

**Comment by jpantana** [comment]
👍 - yeah, the latter one! thx

**Comment by tilleraj** [comment]
Looks fantastic and works great!
There's one bug with the budget overflowing, but Josh fixed it in his upcoming branch
👍

**Comment by Dev-Davis** [comment]
I agree with the wording in the butterfly effect method.

**Pull request merged**
